### ISSUE TITLE
Zip Format throws NullReferenceException 

### ISSUE THREAD

**Issue by ChrisBerna** [neilharvey/FileSignatures#18]
Hi,

I built a simple unit test to check the DetermineFileFormat method for a Zip file and it throws a null referece exception. Here the code snippet:

```csharp
        [Fact]
        public void DetermineFileFormat_ZipByteArray_FormatShouldBeZip()
        {
            var inspector = new FileFormatInspector();
            using (var stream = new MemoryStream(new byte[] { 0x50, 0x4B, 0x03, 0x04 }))
            {
                var format = inspector.DetermineFileFormat(stream);
                format.Should().BeOfType(typeof(Zip));
            }
        }
```

**Comment by neilharvey** [comment]
Hey, this was being caused a bug in the `OpenOfficeXmlFormat` which checks the content of a `ZipArchive` to determine which subformat it contains, but was failing to check whether the instance was null when disposing of it.  Because the test does not create a valid zip archive this meant that the instance constructor failed and so the disposal threw an NRE.

**Comment by neilharvey** [comment]
I've pushed the update to NuGet, should be available shortly.

**Comment by ChrisBerna** [comment]
Thanks a lot!!
