### ISSUE TITLE
Massive Upgrade

### ISSUE THREAD

**Issue by TonyValenti** [neilharvey/FileSignatures#35]
@neilharvey I have recently done a complete rewrite of FileSignatures and added the ability to detect over 14,000 different file types.

I'm interested in publishing my update and, with your permission, taking over the nuget package. Can you contact me at TV@MatterMovers.net to discuss?

**Comment by neilharvey** [comment]
@TonyValenti I notice you've raised a couple of remarkably similar issues in other libraries:

https://github.com/clarkis117/Mime-Detective#36

> Hi @clarkis117 -
> I have recently done a complete rewrite of Mime Detective and added the ability to detect over 14,000 different file types.
>
>I'm interested in publishing my update and, with your permission, taking over maintenance of the nuget package. Can you ? contact me to discuss?

https://github.com/trailmax/filetypedetective#2

> Hi @trailmax -
> I have recently done a complete rewrite of FileTypeDetective and added the ability to detect over 14,000 different file types.
>
> I'm interested in publishing my update and, with your permission, taking over the nuget package. Can you contact me at TV@MatterMovers.net to discuss?

As these libraries have since moved to your ownership, it would appear that you're taking control of various file type detection NuGet packages in order to replace them with your own.  Will it be a commercial product I wonder?

Sorry to disappoint, but I prefer to keep this project open source and am not interesting in handing over control of the library or NuGet package.

**Comment by TonyValenti** [comment]
Hi @neilharvey - 
Everything is definitely staying open open source.

I've been working on a major upgrade for some time now and have incorporated the best of both of these libraries: yours and the ones you mentioned (the two you mentioned are actually forks of each other).

Right now if you look on github, there is a lot of fragmentation among packages. Many people have essentially released identical packages with minor changes. I'm reaching out to those package authors to help clean out the clutter so people aren't using old/unmaintained/unofficial packages.

My hope in reaching out to you is that we could consolidate the official solutions from two into one.
