### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by martinoss** [neilharvey/FileSignatures#73]
@neilharvey How can I reach out to you to report sensitive information?

**Comment by neilharvey** [comment]
Hey, you can contact me through https://www.nuget.org/packages/FileSignatures/5.1.0/ContactOwners

**Comment by neilharvey** [comment]
Thanks, I received your message.  I'll have a think and see what the best solution might be.

That said, you shouldn't consider this library as a concrete way to prevent malicious file uploads because a file could have a valid format but still contain malware - for example a valid PDF could still contain some malicious embedded content.   If you don't trust the origin of a file upload then send it to a virus scanner before doing anything further with it.

**Comment by martinossx** [comment]
I agree, one should not solely depend on such a library to protect from potentially harmful uploads, but it's an important line of defense.

**Comment by martinoss** [comment]
I agree, one should not solely depend on such a library to protect from potentially harmful uploads, but it's an important line of defense.

**Comment by neilharvey** [comment]
Closing - this has been fixed as discussed via email.
